#!/usr/bin/env bash
set -Eeuo pipefail

# Auth-free Squid proxy for Ubuntu/Debian.
# Access is restricted by client source IP/CIDR.
#
# Usage:
#   sudo bash install_proxy.sh [ALLOWED_CLIENT_IP_OR_CIDR] [PROXY_PORT]
#
# Examples:
#   sudo bash install_proxy.sh 203.0.113.25 3128
#   sudo bash install_proxy.sh 203.0.113.0/24 8080
#
# When run over SSH, the client IP is detected automatically if argument 1
# is omitted.

readonly DEFAULT_PORT="3128"
readonly SQUID_CONFIG="/etc/squid/squid.conf"

log()  { printf '\033[1;34m[INFO]\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[ OK ]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[WARN]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[FAIL]\033[0m %s\n' "$*" >&2; exit 1; }

[[ ${EUID:-$(id -u)} -eq 0 ]] || die "Run this script as root: sudo bash $0"

if [[ ! -r /etc/os-release ]]; then
  die "Cannot identify the operating system. This script supports Ubuntu and Debian."
fi
# shellcheck disable=SC1091
source /etc/os-release
case "${ID:-}" in
  ubuntu|debian) ;;
  *) die "Unsupported OS: ${PRETTY_NAME:-unknown}. Use Ubuntu or Debian." ;;
esac

ALLOWED_CLIENT="${1:-}"
PROXY_PORT="${2:-$DEFAULT_PORT}"

if [[ -z "$ALLOWED_CLIENT" && -n "${SSH_CONNECTION:-}" ]]; then
  ALLOWED_CLIENT="${SSH_CONNECTION%% *}"
  log "Detected SSH client IP: $ALLOWED_CLIENT"
fi

if [[ -z "$ALLOWED_CLIENT" ]]; then
  die "Client IP not detected. Run: sudo bash $0 YOUR_PUBLIC_IP [PORT]"
fi

if ! [[ "$PROXY_PORT" =~ ^[0-9]+$ ]] || (( PROXY_PORT < 1024 || PROXY_PORT > 65535 )); then
  die "Proxy port must be an integer from 1024 to 65535."
fi

# Reject deliberately unsafe open-access ranges.
case "$ALLOWED_CLIENT" in
  0.0.0.0/0|::/0|any|ANY)
    die "Refusing to create an open proxy. Provide your public client IP or CIDR."
    ;;
esac

# Validate IPv4/IPv6 address or CIDR using Python's standard ipaddress module.
command -v python3 >/dev/null 2>&1 || {
  log "Installing Python 3 for IP validation..."
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y python3
}
python3 - "$ALLOWED_CLIENT" <<'PY' || die "Invalid client IP/CIDR: $ALLOWED_CLIENT"
import ipaddress
import sys
value = sys.argv[1]
try:
    if "/" in value:
        ipaddress.ip_network(value, strict=False)
    else:
        ipaddress.ip_address(value)
except ValueError:
    raise SystemExit(1)
PY

log "Installing Squid and required utilities..."
apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get install -y squid curl ca-certificates iproute2

command -v squid >/dev/null 2>&1 || die "Squid installation failed."

if ss -ltnH "sport = :$PROXY_PORT" 2>/dev/null | grep -q .; then
  if ! systemctl is-active --quiet squid 2>/dev/null; then
    die "TCP port $PROXY_PORT is already used by another service."
  fi
fi

BACKUP="${SQUID_CONFIG}.backup.$(date +%Y%m%d-%H%M%S)"
if [[ -f "$SQUID_CONFIG" ]]; then
  cp -a "$SQUID_CONFIG" "$BACKUP"
  log "Saved previous Squid configuration to $BACKUP"
fi

cat > "$SQUID_CONFIG" <<EOF
# Generated by install_proxy.sh on $(date -Is)
# Authentication-free proxy restricted to the source IP/CIDR below.

http_port 0.0.0.0:${PROXY_PORT}

# Clients permitted to use the proxy.
acl allowed_client src ${ALLOWED_CLIENT}
acl localhost src 127.0.0.1/32 ::1

# Permit ordinary web traffic only.
acl CONNECT method CONNECT
acl Safe_ports port 80
acl Safe_ports port 443
acl SSL_ports port 443

# Block proxy requests to localhost, link-local, private, and carrier-grade NAT
# destinations to reduce SSRF/pivoting risk.
acl blocked_destinations dst 0.0.0.0/8
acl blocked_destinations dst 10.0.0.0/8
acl blocked_destinations dst 100.64.0.0/10
acl blocked_destinations dst 127.0.0.0/8
acl blocked_destinations dst 169.254.0.0/16
acl blocked_destinations dst 172.16.0.0/12
acl blocked_destinations dst 192.168.0.0/16
acl blocked_destinations dst 224.0.0.0/4
acl blocked_destinations dst 240.0.0.0/4
acl blocked_destinations dst ::1/128
acl blocked_destinations dst fc00::/7
acl blocked_destinations dst fe80::/10

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny blocked_destinations
http_access allow localhost
http_access allow allowed_client
http_access deny all

# Forward proxy privacy and minimal caching.
forwarded_for delete
via off
cache deny all

access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log
coredump_dir /var/spool/squid
EOF

log "Validating Squid configuration..."
squid -k parse >/tmp/squid-parse.log 2>&1 || {
  cat /tmp/squid-parse.log >&2
  [[ -f "$BACKUP" ]] && cp -a "$BACKUP" "$SQUID_CONFIG"
  die "Squid configuration validation failed; the previous configuration was restored."
}

systemctl enable squid >/dev/null
systemctl restart squid
systemctl is-active --quiet squid || {
  journalctl -u squid --no-pager -n 80 >&2 || true
  die "Squid did not start."
}

# If UFW is already active, add only the required source-IP rule. Do not enable
# UFW automatically because doing so could interrupt SSH access.
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active'; then
  if ufw allow proto tcp from "$ALLOWED_CLIENT" to any port "$PROXY_PORT" comment 'Squid proxy' >/dev/null; then
    ok "Added active UFW rule for $ALLOWED_CLIENT -> TCP/$PROXY_PORT"
  else
    warn "Could not add the UFW rule automatically."
  fi
fi

# Confirm local proxy operation. Localhost is intentionally allowed for this test.
TEST_RESULT=""
if TEST_RESULT=$(curl -4fsS --max-time 15 --proxy "http://127.0.0.1:${PROXY_PORT}" https://api.ipify.org 2>/dev/null); then
  ok "Proxy test succeeded; outbound IP: $TEST_RESULT"
else
  warn "Local proxy test could not reach api.ipify.org, but Squid is running and listening."
fi

SERVER_PUBLIC_IP=""
for URL in https://api.ipify.org https://ifconfig.me/ip https://icanhazip.com; do
  SERVER_PUBLIC_IP=$(curl -4fsS --max-time 8 "$URL" 2>/dev/null | tr -d '[:space:]' || true)
  [[ "$SERVER_PUBLIC_IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] && break
  SERVER_PUBLIC_IP=""
done

if [[ -z "$SERVER_PUBLIC_IP" ]]; then
  SERVER_PUBLIC_IP=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") {print $(i+1); exit}}')
fi

ss -ltnp "sport = :$PROXY_PORT" | grep -q squid || die "Squid is not listening on TCP port $PROXY_PORT."

printf '\n\033[1;32mProxy installation completed.\033[0m\n'
printf '--------------------------------------------------\n'
printf 'Proxy type      : HTTP/HTTPS CONNECT\n'
printf 'Proxy IP        : %s\n' "${SERVER_PUBLIC_IP:-UNKNOWN}"
printf 'Proxy port      : %s\n' "$PROXY_PORT"
printf 'Authentication  : None\n'
printf 'Allowed client  : %s\n' "$ALLOWED_CLIENT"
printf 'Proxy URL       : http://%s:%s\n' "${SERVER_PUBLIC_IP:-SERVER_IP}" "$PROXY_PORT"
printf 'Test command    : curl -x http://%s:%s https://api.ipify.org\n' "${SERVER_PUBLIC_IP:-SERVER_IP}" "$PROXY_PORT"
printf '--------------------------------------------------\n'
printf '\nIf the connection is blocked, allow TCP/%s from %s in your cloud provider firewall/security group.\n' "$PROXY_PORT" "$ALLOWED_CLIENT"
